runtime: python27
api_version: 1
threadsafe: false


handlers:
  
- url: /
  script: index.app
  secure: always
  
- url: /index\.html
  script: index.app
  secure: always
  
- url: /main
  script: main.app
  secure: always
  login: required
  
- url: /css
  static_dir: css

- url: /js
  static_dir: js
  
- url: /img
  static_dir: img
  
- url: /fonts
  static_dir: fonts

- url: /update_all_channels
  script: utilities.update_channels.app
  login: admin
  
- url: /update_channels
  script: utilities.update_channels_user.app
  secure: always
  
- url: /task_update_channel
  login: admin
  script: tasks.task_update_channel.app
  secure: always

- url: /api/home
  login: required
  script: api.home.app
  secure: always
  
  
- url: /refresh_subs
  script: refresh_subs.app  
  secure: always
  
- url: /category
  script: category.app  
  secure: always
  login: required
  
- url: /category_list
  script: category_list.app  
  secure: always
  login: required
  
- url: /oauth2callback
  script: main.app
  secure: always
  
- url: /.*
  script: not_found.app 
  secure: always


libraries:
- name: pycrypto
  version: 2.6
- name: ssl
  version: latest
- name: webapp2
  version: "2.5.2"
- name: MySQLdb
  version: "latest"
- name: jinja2
  version: "latest"


  