runtime: python27
api_version: 1
threadsafe: false


handlers:
  
- url: /
  script: main.app
  
- url: /index\.html
  script: main.app
  
- url: /css
  static_dir: css

- url: /js
  static_dir: js
  
- url: /img
  static_dir: img
  
- url: /fonts
  static_dir: fonts

- url: /update_all_channels
  script: utilities.update_channels.app
  login: admin
  
- url: /task_update_channel
  login: admin
  script: tasks.task_update_channel.app

- url: /refresh_subs
  script: refresh_subs.app  

- url: /oauth2callback
  script: main.app
  
- url: /.*
  script: not_found.app 


  
libraries:
- name: pycrypto
  version: 2.6
- name: ssl
  version: latest
- name: webapp2
  version: "2.5.2"
- name: MySQLdb
  version: "latest"
- name: jinja2
  version: "latest"


  